-- 检查并创建activation_history表（如果不存在）

-- 先检查表是否存在
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_tables WHERE tablename = 'activation_history') THEN
        -- 创建activation_history表
        CREATE TABLE activation_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
            code_id BIGINT REFERENCES activation_codes(id) ON DELETE SET NULL,
            plan_type TEXT NOT NULL,
            expires_at TIMESTAMP WITH TIME ZONE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
        
        -- 添加注释
        COMMENT ON TABLE activation_history IS '激活历史记录表';
        COMMENT ON COLUMN activation_history.user_id IS '用户ID';
        COMMENT ON COLUMN activation_history.code_id IS '激活码ID';
        COMMENT ON COLUMN activation_history.plan_type IS '套餐类型';
        COMMENT ON COLUMN activation_history.expires_at IS '过期时间';
        COMMENT ON COLUMN activation_history.created_at IS '创建时间';
        
        -- 启用RLS
        ALTER TABLE activation_history ENABLE ROW LEVEL SECURITY;
        
        -- 创建RLS策略
        CREATE POLICY "Users can view own activation history" ON activation_history
            FOR SELECT USING (auth.uid() = user_id);
            
        CREATE POLICY "Users can insert own activation history" ON activation_history
            FOR INSERT WITH CHECK (auth.uid() = user_id);
            
        RAISE NOTICE 'activation_history表创建成功';
    ELSE
        RAISE NOTICE 'activation_history表已存在';
    END IF;
END $$;

-- 显示表结构信息
SELECT 
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_name = 'activation_history'
ORDER BY ordinal_position;

-- 显示最近的激活历史记录
SELECT 
    ah.id,
    ah.user_id,
    ah.code_id,
    ah.plan_type,
    ah.expires_at,
    ah.created_at,
    ac.code as activation_code
FROM activation_history ah
LEFT JOIN activation_codes ac ON ah.code_id = ac.id
ORDER BY ah.created_at DESC
LIMIT 10;